/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// handwash
// This file was @generated by ai8xize.py --test-dir C:\MaximSDK\Examples\MAX78000\CNN\new-handwash\handwash-demo-64x64 --prefix handwash --overwrite --checkpoint-file trained/ai85-handwash-qat8-q.pth.tar --config-file networks/handwash-hwc.yaml --sample-input tests/sample_handwash64.npy --fifo --softmax --device MAX78000 --timer 0 --display-checkpoint --verbose

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "handwash-2_input.h"

volatile uint32_t cnn_time; // Stopwatch

// Class names for handwash classification (6 classes)
// Update these names based on your training data classes
static const char* class_names[CNN_NUM_OUTPUTS] = {
  "Handwash 1",
  "Handwash 2", 
  "Handwash 3",
  "Handwash 4",
  "Handwash 5",
  "Unknown"
};

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// Data input: HWC 3x64x64 (12288 bytes total / 4096 bytes per channel):
static const uint32_t input_0[] = SAMPLE_INPUT_0;
void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  int i;
  const uint32_t *in0 = input_0;

  for (i = 0; i < 4096; i++) {
    // Remove the following line if there is no risk that the source would overrun the FIFO:
    while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    *((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
  }
}

// Note: check_output() removed for offline testing with custom images
// The original function validated against expected output from sampleoutput.h

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
  cnn_unload((uint32_t *) ml_data);
  softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test handwash ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  cnn_start(); // Start CNN processing
  load_input(); // Load data input via FIFO

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  softmax_layer();

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral

  // Find the best prediction
  int best_class = 0;
  q15_t best_score = ml_softmax[0];
  for (i = 1; i < CNN_NUM_OUTPUTS; i++) {
    if (ml_softmax[i] > best_score) {
      best_score = ml_softmax[i];
      best_class = i;
    }
  }

  printf("Classification results:\n");
  printf("========================\n");
  for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
    digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
    tens = digs % 10;
    digs = digs / 10;
    printf("[%7d] -> Class %d (%s): %d.%d%%%s\n", 
           ml_data[i], i, class_names[i], digs, tens,
           (i == best_class) ? " <-- BEST" : "");
  }
  
  printf("\n========================\n");
  digs = (1000 * ml_softmax[best_class] + 0x4000) >> 15;
  tens = digs % 10;
  digs = digs / 10;
  printf("PREDICTION: Class %d - %s (%d.%d%% confidence)\n", 
         best_class, class_names[best_class], digs, tens);
  printf("========================\n");

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 12,843,264 ops (12,609,024 macc; 234,240 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 1,835,008 ops (1,769,472 macc; 65,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 4,816,896 ops (4,718,592 macc; 98,304 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 4,767,744 ops (4,718,592 macc; 49,152 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 1,198,080 ops (1,179,648 macc; 18,432 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 150,016 ops (147,456 macc; 2,560 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 73,984 ops (73,728 macc; 256 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 1,536 ops (1,536 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 57,264 bytes out of 442,368 bytes total (12.9%)
  Bias memory:   6 bytes out of 2,048 bytes total (0.3%)
*/

